<h1>Личный кабинет</h1>

<?php if(!$isLogin):?>
    Страница доступна только для авторизированных пользователей
    <?php return?>
<?php endif?>

<h2>Список заказов</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aspernatur dolore obcaecati quos voluptatibus. A aliquam dolores dolorum esse exercitationem fugit praesentium qui quo reiciendis sit. Aut ipsam ipsum minus?</p>




